on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the console app
      run: dotnet build --configuration Release
      env:
        DEBUG: "true"

    - name: Check if build output directory exists
    run: |
      if [ ! -d "/Neos yt-dlp Updater/bin/Release/net6.0" ]; then
        echo "Build output directory not found"
        exit 1
      fi

    - name: Zip the built files
      run: zip -r Release.zip bin/Release/net6.0/*

    - name: Upload the release artifact
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: ./Release.zip