name: Build Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the console app
      run: dotnet build --configuration Release

    - name: List contents of the build directory
      run: ls -R bin/Release

    - name: Zip the built files
      run: zip -r Release.zip bin/Release/net6.0/*

    - name: Upload the release artifact
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: ./Release.zip